version: "3.4"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the
# directory that this file is in (`docker/`) and so probably need to start with
# `../` to refer to a directory in the main code checkout

services:
  redis:
    image: redis:5.0.3

  db:
    image: timescale/timescaledb:1.7.4-pg12
    command: postgres -F
    environment:
      POSTGRES_PASSWORD: "postgres"

  rabbitmq:
    image: rabbitmq:3.6.5

  listenbrainz:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: listenbrainz-dev
      args:
        VCS_REF: HEAD
    depends_on:
      - redis
      - db
      - rabbitmq

  frontend_tester:
    build:
      context: ../..
      dockerfile: docker/Dockerfile.webpack
      target: webpack-with-source
