version: "3.4"

# IMPORTANT NOTE: Volume paths mounted on containers are relative to the
# directory that this file is in (`docker/`) and so probably need to start with
# `../` to refer to a directory in the main code checkout

services:

  lb_db:
    image: timescale/timescaledb:2.6.0-pg12
    command: postgres -F
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    image: redis:6.2.2

  listenbrainz:
    build:
      context: ..
      dockerfile: Dockerfile
      target: listenbrainz-dev
    command: py.test listenbrainz/tests/integration
    image: listenbrainz
    volumes:
      - ..:/code/listenbrainz:z
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      SQLALCHEMY_WARN_20: 1
    depends_on:
      - redis
      - lb_db
      - rabbitmq

  timescale_writer:
    image: listenbrainz
    command: python3 -m "listenbrainz.timescale_writer.timescale_writer"
    depends_on:
      - redis
      - lb_db
      - rabbitmq 

  rabbitmq:
    image: rabbitmq:3.8.16
