name: Build image and publish to Docker Hub

on:
  push:
    tags:
      - v-[0-9]+-[0-9]+-[0-9]+.[0-9]+

jobs:

  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    
    - name: Build and push image
      # Github stores the current tag in an enviroment variable (GITHUB_REF) in the format /refs/tags/TAG_NAME. 
      # Using shell parameter expansion, we extract the TAG_NAME.
      run: ./docker/push.sh 'prod' "${GITHUB_REF/refs\/tags\//}"
